In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport
from autoviz.AutoViz_Class import AutoViz_Class
from sklearn.preprocessing import StandardScaler,MinMaxScaler,OneHotEncoder,FunctionTransformer
from sklearn.compose import ColumnTransformer,TransformedTargetRegressor
from imblearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer,KNNImputer
from sklearn.metrics import root_mean_squared_error,r2_score,f1_score,accuracy_score,confusion_matrix, classification_report
from imblearn.over_sampling import SMOTE
import wandb
wandb.login()

True

In [26]:
df = pd.read_csv('heart disease.csv')

In [27]:
df.head()

,male,age,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [28]:
# profile = ProfileReport(df,title='Profiling Report')
# profile.to_file('Report.html')

In [29]:
AV = AutoViz_Class().AutoViz(filename='',dfte=df,depVar='TenYearCHD')

Shape of your Data Set loaded: (4238, 15)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  7
    Number of Integer-Categorical Columns =  1
    Number of String-Categorical Columns =  0
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  0
    Number of Numeric-Boolean Columns =  6
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  0
    Number of Columns to Delete =  0
    14 Predictors classified...
        No variables removed since no ID or low-information variables found in data set

################ Binary_Classification problem #####################
To fix these data quality issues in the dataset, import FixDQ from autoviz...
    All variables classified into correct types.

Total Number of Scatter Plots = 28
All Plots done
Time to run AutoViz = 2 seconds

 ###################### AUTO VISUALIZATION Completed ########################

In [30]:
df.describe()

,male,age,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
count,4238.000000,4238.000000,4238.000000,4209.000000,4185.000000,4238.000000,4238.000000,4238.000000,4188.000000,4238.000000,4238.000000,4219.000000,4237.000000,3850.000000,4238.000000
mean,0.429212,49.584946,0.494101,9.003089,0.029630,0.005899,0.310524,0.025720,236.721585,132.352407,82.893464,25.802008,75.878924,81.966753,0.151958
std,0.495022,8.572160,0.500024,11.920094,0.169584,0.076587,0.462763,0.158316,44.590334,22.038097,11.910850,4.080111,12.026596,23.959998,0.359023
min,0.000000,32.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,107.000000,83.500000,48.000000,15.540000,44.000000,40.000000,0.000000
25%,0.000000,42.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,206.000000,117.000000,75.000000,23.070000,68.000000,71.000000,0.000000
50%,0.000000,49.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,234.000000,128.000000,82.000000,25.400000,75.000000,78.000000,0.000000
75%,1.000000,56.000000,1.000000,20.000000,0.000000,0.000000,1.000000,0.000000,263.000000,144.000000,89.875000,28.040000,83.000000,87.000000,0.000000
max,1.000000,70.000000,1.000000,70.000000,1.000000,1.000000,1.000000,1.000000,696.000000,295.000000,142.500000,56.800000,143.000000,394.000000,1.000000

In [31]:
from sklearn.metrics import confusion_matrix, classification_report

def model_scoring(model, X_train, X_test, y_train, y_test):
    # ---- Test Set ----
    y_test_pred = model.predict(X_test)
    print("\n=== Test Set Evaluation ===")
    print("\nConfusion Matrix (Test Set):\n", confusion_matrix(y_test, y_test_pred))
    print("\nClassification Report (Test Set):\n", classification_report(y_test, y_test_pred))

    print("-" * 50)

    # ---- Train Set ----
    y_train_pred = model.predict(X_train)
    print("\n=== Train Set Evaluation ===")
    print("\nConfusion Matrix (Train Set):\n", confusion_matrix(y_train, y_train_pred))
    print("\nClassification Report (Train Set):\n", classification_report(y_train, y_train_pred))

In [32]:
df.head()

,male,age,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

### Simple Imputer

In [33]:
def logistic_1(data):
    df = data.copy()

    target = 'TenYearCHD'
    X = df.drop(columns=target)
    y = df[target]
    
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

    mean_features = ['totChol','glucose','cigsPerDay','BMI','heartRate']
    median_features = ['BPMeds']

    mean_pipeline = Pipeline([
        ('imputer',SimpleImputer(strategy='mean'))
    ])

    median_pipeline = Pipeline([
        ('imputer',SimpleImputer(strategy='median'))
    ])

    preprocessor = ColumnTransformer([
        ('num',mean_pipeline,mean_features),
        ('cat',median_pipeline,median_features)   
    ],remainder='passthrough'
    )

    regression_pipeline = Pipeline([
        ('preprocessor',preprocessor),
        ('scaler',StandardScaler()),
        ('model',LogisticRegression(random_state=42))
    ])

    regression_pipeline.fit(X_train,y_train)

    model_scoring(regression_pipeline,X_train,X_test,y_train,y_test)

In [34]:
logistic_1(df)

=== Test Set Evaluation ===

Confusion Matrix (Test Set):
 [[710   9]
 [120   9]]

Classification Report (Test Set):
               precision    recall  f1-score   support

           0       0.86      0.99      0.92       719
           1       0.50      0.07      0.12       129

    accuracy                           0.85       848
   macro avg       0.68      0.53      0.52       848
weighted avg       0.80      0.85      0.80       848

--------------------------------------------------

=== Train Set Evaluation ===

Confusion Matrix (Train Set):
 [[2859   16]
 [ 467   48]]

Classification Report (Train Set):
               precision    recall  f1-score   support

           0       0.86      0.99      0.92      2875
           1       0.75      0.09      0.17       515

    accuracy                           0.86      3390
   macro avg       0.80      0.54      0.54      3390
weighted avg       0.84      0.86      0.81      3390

### KNNImputer

In [35]:
def logistic_2(data):
    df = data.copy()

    target = 'TenYearCHD'
    X = df.drop(columns=target)
    y = df[target]
    
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

    pipeline = Pipeline([
    ('scaler', StandardScaler()),    
    ('imputer', KNNImputer(n_neighbors=5)),
    ('model', LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced'))
    ])

    pipeline.fit(X_train,y_train)

    model_scoring(pipeline,X_train,X_test,y_train,y_test)

In [36]:
logistic_2(df)

=== Test Set Evaluation ===

Confusion Matrix (Test Set):
 [[492 227]
 [ 54  75]]

Classification Report (Test Set):
               precision    recall  f1-score   support

           0       0.90      0.68      0.78       719
           1       0.25      0.58      0.35       129

    accuracy                           0.67       848
   macro avg       0.57      0.63      0.56       848
weighted avg       0.80      0.67      0.71       848

--------------------------------------------------

=== Train Set Evaluation ===

Confusion Matrix (Train Set):
 [[1943  932]
 [ 157  358]]

Classification Report (Train Set):
               precision    recall  f1-score   support

           0       0.93      0.68      0.78      2875
           1       0.28      0.70      0.40       515

    accuracy                           0.68      3390
   macro avg       0.60      0.69      0.59      3390
weighted avg       0.83      0.68      0.72      3390

### SMOTE for oversampling to reduce class Imbalance

In [37]:
def logistic_3(data):
    df = data.copy()

    target = 'TenYearCHD'
    X = df.drop(columns=target)
    y = df[target]
    
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

    pipeline = Pipeline([
    ('scaler', StandardScaler()),    
    ('imputer', KNNImputer(n_neighbors=5)),
    ('smote', SMOTE(random_state=42)),
    ('model', LogisticRegression(max_iter=1000, random_state=42))
    ])

    pipeline.fit(X_train,y_train)

    model_scoring(pipeline,X_train,X_test,y_train,y_test)

In [38]:
logistic_3(df)

=== Test Set Evaluation ===

Confusion Matrix (Test Set):
 [[486 233]
 [ 53  76]]

Classification Report (Test Set):
               precision    recall  f1-score   support

           0       0.90      0.68      0.77       719
           1       0.25      0.59      0.35       129

    accuracy                           0.66       848
   macro avg       0.57      0.63      0.56       848
weighted avg       0.80      0.66      0.71       848

--------------------------------------------------

=== Train Set Evaluation ===

Confusion Matrix (Train Set):
 [[1922  953]
 [ 158  357]]

Classification Report (Train Set):
               precision    recall  f1-score   support

           0       0.92      0.67      0.78      2875
           1       0.27      0.69      0.39       515

    accuracy                           0.67      3390
   macro avg       0.60      0.68      0.58      3390
weighted avg       0.83      0.67      0.72      3390

### Outlier Removal

In [39]:
# Function to detect outlier rows using IQR
def detect_outliers_iqr(data, columns):
    outlier_indices = set()
    for col in columns:
        Q1 = np.percentile(data[col].dropna(), 25)
        Q3 = np.percentile(data[col].dropna(), 75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        outliers = data[(data[col] < lower_bound) | (data[col] > upper_bound)].index
        outlier_indices.update(outliers)
    return list(outlier_indices)

In [40]:
def logistic_4(data):
    df = data.copy()

    # Define numerical columns where outliers make sense
    num_cols = ['age', 'cigsPerDay', 'totChol', 'sysBP', 'diaBP', 'BMI', 'heartRate', 'glucose']

    outlier_rows = detect_outliers_iqr(df, num_cols)

    df_no_outliers = df.drop(index=outlier_rows).reset_index(drop=True)

    target = 'TenYearCHD'
    X = df_no_outliers.drop(columns=target)
    y = df_no_outliers[target]
    
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

    pipeline = Pipeline([
    ('scaler', StandardScaler()),    
    ('imputer', KNNImputer(n_neighbors=5)),
    ('smote', SMOTE(random_state=42)),
    ('model', LogisticRegression(max_iter=1000, random_state=42))
    ])

    pipeline.fit(X_train,y_train)

    model_scoring(pipeline,X_train,X_test,y_train,y_test)

In [41]:
logistic_4(df)

=== Test Set Evaluation ===

Confusion Matrix (Test Set):
 [[428 217]
 [ 32  68]]

Classification Report (Test Set):
               precision    recall  f1-score   support

           0       0.93      0.66      0.77       645
           1       0.24      0.68      0.35       100

    accuracy                           0.67       745
   macro avg       0.58      0.67      0.56       745
weighted avg       0.84      0.67      0.72       745

--------------------------------------------------

=== Train Set Evaluation ===

Confusion Matrix (Train Set):
 [[1708  868]
 [ 126  274]]

Classification Report (Train Set):
               precision    recall  f1-score   support

           0       0.93      0.66      0.77      2576
           1       0.24      0.69      0.36       400

    accuracy                           0.67      2976
   macro avg       0.59      0.67      0.56      2976
weighted avg       0.84      0.67      0.72      2976

### Outlier Capping

In [42]:
def cap_outliers_iqr(data, columns):
    capped_data = data.copy()
    for col in columns:
        Q1 = np.percentile(capped_data[col].dropna(), 25)
        Q3 = np.percentile(capped_data[col].dropna(), 75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        # Cap the values outside the bounds
        capped_data[col] = np.where(
            capped_data[col] < lower_bound, lower_bound,
            np.where(capped_data[col] > upper_bound, upper_bound, capped_data[col])
        )
    return capped_data

In [43]:
def logistic_5(data):
    df = data.copy()

    # Define numerical columns where outliers make sense
    num_cols = ['age', 'cigsPerDay', 'totChol', 'sysBP', 'diaBP', 'BMI', 'heartRate', 'glucose']

    df_capped_outliers = cap_outliers_iqr(df, num_cols)

    target = 'TenYearCHD'
    X = df_capped_outliers.drop(columns=target)
    y = df_capped_outliers[target]
    
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

    pipeline = Pipeline([
    ('scaler', StandardScaler()),    
    ('imputer', KNNImputer(n_neighbors=5)),
    ('smote', SMOTE(random_state=42)),
    ('model', LogisticRegression(max_iter=1000, random_state=42))
    ])

    pipeline.fit(X_train,y_train)

    model_scoring(pipeline,X_train,X_test,y_train,y_test)

In [44]:
logistic_5(df)

=== Test Set Evaluation ===

Confusion Matrix (Test Set):
 [[493 226]
 [ 55  74]]

Classification Report (Test Set):
               precision    recall  f1-score   support

           0       0.90      0.69      0.78       719
           1       0.25      0.57      0.34       129

    accuracy                           0.67       848
   macro avg       0.57      0.63      0.56       848
weighted avg       0.80      0.67      0.71       848

--------------------------------------------------

=== Train Set Evaluation ===

Confusion Matrix (Train Set):
 [[1923  952]
 [ 155  360]]

Classification Report (Train Set):
               precision    recall  f1-score   support

           0       0.93      0.67      0.78      2875
           1       0.27      0.70      0.39       515

    accuracy                           0.67      3390
   macro avg       0.60      0.68      0.59      3390
weighted avg       0.83      0.67      0.72      3390

### Additionally combined with outlier capping or removing

In [45]:
from sklearn.base import BaseEstimator, TransformerMixin
class OutlierCapperOrRemover(BaseEstimator, TransformerMixin):
    """
    Scikit-learn compatible transformer to cap or remove outliers based on IQR method.

    Parameters:
    ----------
    strategy : str, optional (default='cap')
        Strategy to handle outliers: 
        'cap' - clip values to IQR bounds, 
        'remove' - remove rows containing outliers.
    
    factor : float, optional (default=1.5)
        The multiplication factor for IQR to define outlier boundaries (standard = 1.5).
    
    columns : list, optional (default=None)
        List of column names to apply outlier handling on. 
        If None, will apply to all numeric columns.
    """
    def __init__(self, strategy='cap', factor=1.5, columns=None):
        self.strategy = strategy
        self.factor = factor
        self.columns = columns
        self.bounds_ = {}

    def fit(self, X, y=None):
        """
        Learn the IQR bounds for each feature.
        """
        X = X.copy()
        if self.columns is None:
            self.columns = X.select_dtypes(include=[np.number]).columns.tolist()
        
        for col in self.columns:
            Q1 = np.percentile(X[col].dropna(), 25)
            Q3 = np.percentile(X[col].dropna(), 75)
            IQR = Q3 - Q1
            lower_bound = Q1 - self.factor * IQR
            upper_bound = Q3 + self.factor * IQR
            self.bounds_[col] = (lower_bound, upper_bound)
        
        return self

    def transform(self, X):
        """
        Apply capping or removal based on learned bounds.
        """
        X = X.copy()
        
        if self.strategy == 'cap':
            for col, (lower, upper) in self.bounds_.items():
                X[col] = np.clip(X[col], lower, upper)
            return X

        elif self.strategy == 'remove':
            for col, (lower, upper) in self.bounds_.items():
                X = X[(X[col] >= lower) & (X[col] <= upper)]
            X = X.reset_index(drop=True)
            return X

        else:
            raise ValueError("Strategy must be either 'cap' or 'remove'.")

In [46]:
def logistic_6_with_gridsearch(data):
    df = data.copy()

    target = 'TenYearCHD'
    X = df.drop(columns=target)
    y = df[target]
    
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    # Save feature names
    feature_names = X_train.columns.tolist()

    pipeline = Pipeline([
        ('outlier_handler', OutlierCapperOrRemover(strategy='cap', factor=1.5)),
        ('imputer', KNNImputer(n_neighbors=5)),
        ('scaler', StandardScaler()),
        ('smote', SMOTE(random_state=42)),
        ('model', LogisticRegression(max_iter=1000, random_state=42))
    ])



    # Define hyperparameter grid
    param_grid = {
        'model__C': [0.01, 0.1, 1, 10, 100],         # Regularization strength
        'model__penalty': ['l2'],                    # Only 'l2' for Logistic Regression with solvers like 'lbfgs'
        'model__solver': ['lbfgs', 'saga']            # Solvers that handle l2 regularization
    }

    # Set up GridSearchCV
    grid = GridSearchCV(
        pipeline,
        param_grid,
        cv=5,               # 5-fold cross-validation
        scoring='f1',       # Optimize for F1 score (good for imbalance)
        n_jobs=-1,          # Parallelize across CPU cores
        verbose=1           # Show progress
    )

    # Fit grid search
    grid.fit(X_train, y_train)

    # Best estimator found
    best_pipeline = grid.best_estimator_
    print("\nBest hyperparameters:", grid.best_params_)

    # Evaluate best model
    model_scoring(best_pipeline, X_train, X_test, y_train, y_test)

In [47]:
logistic_6_with_gridsearch(df)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

Best hyperparameters: {'model__C': 0.01, 'model__penalty': 'l2', 'model__solver': 'lbfgs'}

=== Test Set Evaluation ===

Confusion Matrix (Test Set):
 [[479 240]
 [ 50  79]]

Classification Report (Test Set):
               precision    recall  f1-score   support

           0       0.91      0.67      0.77       719
           1       0.25      0.61      0.35       129

    accuracy                           0.66       848
   macro avg       0.58      0.64      0.56       848
weighted avg       0.81      0.66      0.70       848

--------------------------------------------------

=== Train Set Evaluation ===

Confusion Matrix (Train Set):
 [[1901  974]
 [ 159  356]]

Classification Report (Train Set):
               precision    recall  f1-score   support

           0       0.92      0.66      0.77      2875
           1       0.27      0.69      0.39       515

    accuracy                           0.67      3390
   macro avg       0.60      0.68      0.58      3390
weighted avg       0.82      0.67      0.71      3390

In [ ]:
logistic_6_with_gridsearch(data=df.drop(columns=['currentSmoker','diabetes','diaBP','prevalentHyp']))

Fitting 5 folds for each of 10 candidates, totalling 50 fits

Best hyperparameters: {'model__C': 0.1, 'model__penalty': 'l2', 'model__solver': 'lbfgs'}

=== Test Set Evaluation ===

Confusion Matrix (Test Set):
 [[482 237]
 [ 52  77]]

Classification Report (Test Set):
               precision    recall  f1-score   support

           0       0.90      0.67      0.77       719
           1       0.25      0.60      0.35       129

    accuracy                           0.66       848
   macro avg       0.57      0.63      0.56       848
weighted avg       0.80      0.66      0.71       848

--------------------------------------------------

=== Train Set Evaluation ===

Confusion Matrix (Train Set):
 [[1910  965]
 [ 158  357]]

Classification Report (Train Set):
               precision    recall  f1-score   support

           0       0.92      0.66      0.77      2875
           1       0.27      0.69      0.39       515

    accuracy                           0.67      3390
   macro avg       0.60      0.68      0.58      3390
weighted avg       0.82      0.67      0.71      3390

Exception ignored in: <function ResourceTracker.__del__ at 0x1045c5b20>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x105d89b20>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x1038e1b20>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x1044b1b20>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x107771b20>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x10721db20>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x107589b20>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x102b9db20>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/anaconda3/envs/ml/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes